
export const localimag = {
    crossb: require('./icons/cancelb.png'),
    crossw: require('./icons/cancelw.png'),
    arrowl: require('./icons/backl.png'),
    arrowld: require('./icons/backlb.png'),
    arrowr: require('./icons/backr.png'),
    arrowlw: require('./icons/backlw.png'),
    maplocation: require('./icons/location.png'),
   

    //------------my image-----------------//
  //  splash: require('../../Icons/splash.png'),
    
  backgroud_gradient:require('../../Icons/backgroud_gradient.png'),
  icon_back:require('../../Icons/icon_back.png'),
  icon_close_white:require('../../Icons/icon_close_white.png'),
  icon_close:require('../../Icons/icon_close.png'),
  icon_down_white:require('../../Icons/icon_down_white.png'),
  icon_down:require('../../Icons/icon_down.png'),
  icon_eye:require('../../Icons/icon_eye.png'),
  icon_eye_hide:require('../../Icons/icon_eye_hide.png'),

  icon_link:require('../../Icons/icon_link.png'),
  icon_star:require('../../Icons/icon_star.png'),
  icon_time_white:require('../../Icons/icon_time_white.png'),
  icon_up_white:require('../../Icons/icon_up_white.png'),
  icon_up:require('../../Icons/icon_up.png'),
  logo_white:require('../../Icons/logo_white.png'),
  logo:require('../../Icons/logo.png'),
  round_shape:require('../../Icons/round_shape.png'),
  icon_setting:require('../../Icons/icon_setting.png'),
  icon_bedges:require('../../Icons/icon_bedges.png'),
  icon_ractangle:require('../../Icons/icon_ractangle.png'),
  icon_delete:require('../../Icons/icon_delete.png'),
  icon_download:require('../../Icons/icon_download.png'),
  icon_challenger1:require('../../Icons/icon_challenger1.png'),
  icon_challenger2:require('../../Icons/icon_challenger2.png'),
  icon_challenger3:require('../../Icons/icon_challenger3.png'),
  icon_challenger4:require('../../Icons/icon_challenger4.png'),
  icon_Check:require('../../Icons/icon_Check.png'),
  icon_shape2:require('../../Icons/icon_shape2.png'),
  icon_ellipse:require('../../Icons/icon_ellipse.png'),
  icon_filter:require('../../Icons/icon_filter.png'),
  icon_home:require('../../Icons/icon_home.png'),
  icon_next:require('../../Icons/icon_next.png'),
  icon_leftTab:require('../../Icons/icon_leftTab.png'),
  icon_rightTab:require('../../Icons/icon_rightTab.png'),
  icon_play:require('../../Icons/icon_play.png'),
  icon_pause:require('../../Icons/icon_pause.png'),
  icon_left_skip:require('../../Icons/icon_left_skip.png'),
  icon_right_skip:require('../../Icons/icon_right_skip.png'),
  icon_volume:require('../../Icons/icon_volume.png'),
  icon_enable_sound:require('../../Icons/icon_enable_sound.png'),
  icon_left_arrow:require('../../Icons/icon_left_arrow.png'),
  icon_right_arrow:require('../../Icons/icon_right_arrow.png'),
  icon_video_up:require('../../Icons/icon_video_up.png'),
  icon_video_down:require('../../Icons/icon_video_down.png'),
  icon_1:require('../../Icons/icon_1.png'),
  icon_2:require('../../Icons/icon_2.png'),
  icon_3:require('../../Icons/icon_3.png'),
  icon_watch:require('../../Icons/icon_watch.png'),
  Camera_icon:require('../../Icons/Camera_icon.png'),
  right_icon_image:require('../../Icons/right_icon_image.png'),
  left_icon_image:require('../../Icons/left_icon_image.png'),
  Icon_beginner_badge:require('../../Icons/Icon_beginner_badge.png'),
  icon_elite_badge:require('../../Icons/icon_elite_badge.png'),
  icon_savage_badge:require('../../Icons/icon_savage_badge.png'),
  icon_doc:require('../../Icons/icon_doc.png'),
  icon_home_w:require('../../Icons/icon_home_w.png'),
  icon_plus:require('../../Icons/icon_plus.png'),


  
}
